### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create the index.html, styles.css, and main.js files.
- [x] Set the title as Driving Game.
- [x] Pick a background color.
- [x] Pick a car image and add it to the images folder.
- [x] Style the car in the top left corner.
