### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS classes for each car position
- [x] Create a car data model that stores the car position.
- [x] Listen for 'keydown' events on the document.
- [x] Update the car position according to which arrow key is pressed.
- [x] Assign the car position into the car data model.
