### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by KiannaBrandt** [KiannaBrandt/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Apply `position: absolute` to the car.
- [x] Listen for the spacebar `'keydown'` event on the document.
- [x] Use the `setInterval()` method to move the car every 16 milliseconds.
- [x] Change the car's style left property to move from the left 5 pixels.
